[package]
name = "dapr"
version = "0.12.0"
authors = ["dapr.io"]
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/dapr/rust-sdk"
description = "Rust SDK for dapr"
readme = "README.md"
keywords = ["microservices", "dapr"]


[dependencies]
futures = "0.3"
tonic = "0.8"
prost = "0.11"
bytes = "1"
prost-types = "0.11"
async-trait = "0.1"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.3"
chrono = "0.4.24"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[[example]]
name = "client"
path = "examples/client/client.rs"

[[example]]
name = "publisher"
path = "examples/pubsub/publisher.rs"

[[example]]
name = "subscriber"
path = "examples/pubsub/subscriber.rs"

[[example]]
name = "invoke-grpc-client"
path = "examples/invoke/grpc/client.rs"

[[example]]
name = "invoke-grpc-server"
path = "examples/invoke/grpc/server.rs"

[[example]]
name = "invoke-grpc-proxying-client"
path = "examples/invoke/grpc-proxying/client.rs"

[[example]]
name = "invoke-grpc-proxying-server"
path = "examples/invoke/grpc-proxying/server.rs"

[[example]]
name = "actor-client"
path = "examples/actors/client.rs"

[[example]]
name = "actor-server"
path = "examples/actors/server.rs"
